[global]
bind = "127.0.0.1:3000"
limit = false

[tls]
tls = true
auto_cert = false
cert_path = "credentials/_wildcard.local.porto.pem"
key_path = "credentials/_wildcard.local.porto-key.pem"

[[proxy]]
domain = "darius.local.porto"
upstream = "127.0.0.2:8000"

