[env]
# embeds MALLOC_CONF runtime options at build time
# see https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md for more settings
JEMALLOC_SYS_WITH_MALLOC_CONF = "background_thread:true,narenas:4,dirty_decay_ms:1000,muzzy_decay_ms:500"
